openapi: 3.1.0
info:
  title: Cargospot Handling Components
  description: Common components for Cargospot Handling REST APIs
  version: v1
components:
  schemas:
    AirWaybillNumber:
      type: object
      required:
        - prefix
        - serial
      properties:
        prefix:
          type: string
          description: Prefix of the air waybill.
          example: 950
        serial:
          type: string
          description: Serial number of the air waybill.
          example: 12345678
    BookedWeight:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          description: Booked Weight.
          format: float
          example: 3000
        unit:
          type: string
          description: Weight unit. KG indicates Kilogram.
          example: KG
          enum:
            - KG
    Carrier:
      type: object
      properties:
        code:
          type: string
          description: ICAO airline designator, coded identification for a carrier.
          example: XS
        name:
          type: string
          description: Carrier name.
          example: CHAMP
    ChargeableWeight:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          description: Chargeable Weight.
          format: float
          example: 3000
        unit:
          type: string
          description: Weight unit. KG indicates Kilogram.
          example: KG
          enum:
            - KG
    Country:
      type: object
      properties:
        code:
          type: string
          description: ISO 2-letter country code.
          example: US
        name:
          type: string
          description: Country name.
          example: United States of America
    DeliveryId:
      type: string
      description: Unique identifier for the delivery record.
      examples:
        - 33546822
    Dimension:
      type: object
      required:
        - measurements
        - unit
      properties:
        measurements:
          type: array
          items:
            $ref: "#/components/schemas/Measurements"
        unit:
          type: string
          description: Unit for length, width and height. CMT indicates centimeters; INH indicates inches.
          enum:
            - CMT
            - INH
          default: CMT
          example: CMT
    DimensionDetails:
      type: object
      properties:
        measurements:
          type: array
          items:
            $ref: "#/components/schemas/MeasurementDetails"
        unit:
          type: string
          description: Unit for length, width and height. CMT indicates centimeters; INH indicates inches.
          enum:
            - CMT
            - INH
          default: CMT
          example: CMT
    Driver:
      required:
        - callForwardTicket
        - licencePlate
        - name
        - passNumber
      type: object
      properties:
        callForwardTicket:
          type: string
          description: Number of the call forward ticket.
          example: IMP23SEP19MAN0001
        name:
          type: string
          description: Name of the driver.
          example: Any Name
        licencePlate:
          type: string
          description: Vehicle licence plate number.
          example: HH71ABC
        passNumber:
          type: string
          description: Pass number of the vehicle.
          example: 12345F
    DryIceWeight:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          description: DryIce Weight.
          format: float
          example: 3000
        unit:
          type: string
          description: Weight unit. KG indicates Kilogram.
          example: KG
          enum:
            - KG
    HandlingInformation:
      type: object
      properties:
        description:
          type: string
          description: Handling information.
          example: Keep up right
        source:
          type: string
          description: Source of handling information.
          example: manual
          enum:
            - FWB
            - FHL
            - FBL
            - FFM
            - manual
        type:
          type: string
          enum:
            - SSR
            - OSI
          description: Type of handling information.
          example: SSR
    Irregularity:
      type: object
      properties:
        irregularityType:
          $ref: "#/components/schemas/IrregularityType"
        pieces:
          type: integer
          format: int32
          description: Number of pieces.
          example: 1
        weight:
          $ref: "#/components/schemas/WeightWithUnit"
    IrregularityType:
      type: object
      properties:
        code:
          type: string
          description: Irregularity code.
          example: 17
        name:
          type: string
          description: Description of irregularity.
          example: BOOKING DEVIATION AT ACCEPTANCE
    Location:
      type: object
      properties:
        code:
          type: string
          description: 3-letter-IATA code.
          example: BCN
        name:
          type: string
          description: Full name.
          example: Barcelona
        type:
          type: string
          enum:
            - Airport
            - City
          description: Indicates if airport or city.
          example: Airport
    LocationWithTimeArea:
      type: object
      properties:
        code:
          type: string
          description: 3-letter-IATA code of the location.
          example: SIN
        name:
          type: string
          description: Full name of the location.
          example: Singapore
        type:
          type: string
          enum:
            - Airport
            - City
          description: Indicates if airport or city.
          example: Airport
        timeArea:
          type: string
          description: Time area.
          example: Asia/Singapore
        utcOffset:
          type: integer
          format: int32
          description: This is the UTC offset for this airport/city as on the date/time at which the response was created.
          example: 480
    Measurements:
      type: object
      required:
        - pieces
        - weight
        - length
        - width
        - height
      properties:
        pieces:
          type: integer
          format: int32
          description: Pieces.
          example: 1
        weight:
          $ref: "#/components/schemas/Weight"
        length:
          type: integer
          format: int32
          description: Length.
          example: 100
        width:
          type: integer
          format: int32
          description: Width.
          example: 80
        height:
          type: integer
          format: int32
          description: Height.
          example: 60
    MeasurementDetails:
      type: object
      properties:
        pieces:
          type: integer
          format: int32
          description: Pieces.
          example: 1
        weight:
          $ref: "#/components/schemas/WeightWithUnit"
        length:
          type: integer
          format: int32
          description: Length.
          example: 100
        width:
          type: integer
          format: int32
          description: Width.
          example: 80
        height:
          type: integer
          format: int32
          description: Height.
          example: 60
    MeasurementWithUnit:
      type: object
      properties:
        amount:
          type: number
          description: Height, Length or Breadth.
          format: float
          example: 100
        unit:
          type: string
          description: Unit. CM indicates Centimeter.
          example: CM
          enum:
            - CM
    PartId:
      type: string
      description: Unique Cargospot internal ID for the part shipment.
      examples:
        - 1981
    PartLevelDimensionDetails:
      type: object
      properties:
        pieces:
          type: integer
          format: int32
          description: Pieces.
          example: 1
        weight:
          $ref: "#/components/schemas/WeightWithUnit"
        volume:
          $ref: "#/components/schemas/VolumeWithUnit"
        length:
          type: integer
          format: int32
          description: Length.
          example: 100
        width:
          type: integer
          format: int32
          description: Width.
          example: 80
        height:
          type: integer
          format: int32
          description: Height.
          example: 60
        unit:
          type: string
          description: Unit for length, width and height. CMT indicates centimeters; INH indicates inches.
          enum:
            - CMT
            - INH
          default: CMT
          example: CMT
        sequence:
          type: string
          description: Combination of air waybill sequence number, partNumber and ordernumber of measurement rows.
          example: 16258-1-1
        partNumber:
          type: string
          description: Part number of the shipment.
          example: 1
    PickupDriver:
      required:
        - name
      type: object
      properties:
        callForwardTicket:
          type: string
          description: Number of the call forward ticket. This information will be required for specific Cargospot instances.
          example: IMP23SEP19MAN0001
        name:
          type: string
          description: Delivery details information. To enter delivery related information. The field can be used differently. The name of the pick-up person or pickup person ID can be entered. This information will appear on the printed delivery receipt.
          example: JOE
        licencePlate:
          type: string
          description: Delivery details information. To enter additional delivery related information. The field can be used differently. The vehicle license plate number, license number or the airport ID code of  the pick-up person can be entered. This information will appear on the printed delivery receipt.
          example: HH71ABC
        passNumber:
          type: string
          description: Delivery details information. To enter additional delivery related information. The field can be used differently. Passnumber or phone number can be entered.
          example: 12345F
    NumberOfPieces:
      type: integer
      description: Number of pieces.
      examples:
        - 2
    PiecesStoredLocation:
      type: object
      properties:
        numberOfPieces:
          $ref: "#/components/schemas/NumberOfPieces"
        weight:
          $ref: "#/components/schemas/WeightWithUnit"
        groupLabel:
          type: string
          description: Group label number for the pieces.
          example: 3210-01
        storageLocationCode:
          type: string
          description: Storage location code.
          example: EXP-A
    ReadyForCarriageCheckDetails:
      type: object
      properties:
        code:
          type: string
          description: Code of the required RFC check.
          example: FWB
        name:
          type: string
          description: Name of the required RFC check.
          example: FWB Received
        status:
          type: boolean
          description: Indicates whether the check has been completed or not. true indicates that the check has been completed.
          example: true
    ReadyForCarriageCheck:
      type: object
      required:
        - code
        - status
      properties:
        code:
          type: string
          description: Code of the required RFC check.
          example: FWB
        status:
          type: boolean
          description: Indicates whether the check has been completed or not. true indicates that the check has been completed.
          example: true
    RecievingAgentAccountNumber:
      type: string
      description: Account number of the recieving agent.
      examples:
        - 8147000210
    OtherCustomsInformation:
      type: object
      properties:
        country:
          $ref: "#/components/schemas/Country"
        informationIdentifier:
          type: string
          description: Information Identifier. Code identifying a particular group of data elements. Examples AGT, SSI, ABI.
          example: SHP
        customsControlInformation:
          type: string
          description: Customs, Security and Regulatory Control Information Identifier. Coded indicator qualifying Customs, Security and Regulatory Control related information. Examples CP, CT, ED.
          example: C
        supplementaryInformation:
          type: string
          description: Supplementary Customs, Security and Regulatory Control Information. Supplementary information identifying a party or a location related to Customs, Security and Regulatory Control reporting requirements.
          example: LEO
        source:
          type: string
          description: Regulatory Control Information source.
          example: OCI
    Status:
      type: object
      properties:
        code:
          type: string
          description: Status code.
          example: OK
        description:
          type: string
          description: Status description.
          example: Acceptance cut-off not exceeded
    TransportMeansResource:
      type: object
      properties:
        id:
          type: string
          description: Unique Cargospot internal ID for this flight/truck.
          example: 485755
        carrier:
          $ref: "#/components/schemas/Carrier"
        date:
          type: string
          format: date
          description: The date of the transport means. Flight / truck date in format YYYY-MM-DD.
          example: 2021-09-06
        mode:
          type: string
          description: May not return in all case, Review and remove-TBD
          example: TBD
        reference:
          type: string
          description: Business reference for the flight/truck.
          example: XS515A/06SEP
        scheduledArrival:
          type: string
          format: dateTime
          description: Scheduled date of arrival.
          example: 2021-09-15 0800
        scheduledDeparture:
          type: string
          format: dateTime
          description: Scheduled date of departure.
          example: 2021-09-15 0200
        transportNumber:
          type: string
          description: Reference number for the flight/truck (e.g. flight number).
          example: 515A
        aircraftType:
          type: string
          description: Aircraft type code.
          example: 777
    ValidationOverride:
      type: object
      required:
        - httpCode
        - businessErrorCode
      properties:
        httpCode:
          type: string
          description: http response code.
          example: "422"
        businessErrorCode:
          type: string
          description: Error code for the business error.
          example: ULDAcceptanceExceedsCutOff
    Volume:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          description: Volume.
          format: float
          example: 24
        unit:
          type: string
          description: Volume unit. MC indicates cubic metre.
          example: MC
          enum:
            - MC
    VolumeWithUnit:
      type: object
      properties:
        amount:
          type: number
          description: Volume.
          format: float
          example: 24
        unit:
          type: string
          description: Volume unit. MC indicates cubic metre.
          example: MC
          enum:
            - MC
    WarehouseLocation:
      type: object
      properties:
        code:
          $ref: "#/components/schemas/WarehouseLocationCode"
        name:
          $ref: "#/components/schemas/WarehouseLocationName"
    WarehouseLocationCode:
      type: string
      description: Location code.
      examples:
        - IMPORT
    WarehouseLocationName:
      type: string
      description: Location name.
      examples:
        - IMPORT
    Weight:
      type: object
      required:
        - amount
        - unit
      properties:
        amount:
          type: number
          description: Weight.
          format: float
          example: 3000
        unit:
          type: string
          description: Weight unit. KG indicates Kilogram.
          example: KG
          enum:
            - KG
    WeightTolerance:
      type: object
      properties:
        minimum:
          $ref: "#/components/schemas/WeightWithUnit"
        maximum:
          $ref: "#/components/schemas/WeightWithUnit"
    WeightWithUnit:
      type: object
      properties:
        amount:
          type: number
          description: Weight.
          format: float
          example: 3000
        unit:
          type: string
          description: Weight unit. KG indicates Kilogram.
          example: KG
          enum:
            - KG
  parameters:
    stationCode:
      name: stationCode
      in: header
      description: 3-letter IATA code of the station at which this transaction is being recorded.
      required: true
      schema:
        type: string
        examples:
          - LHR
    airWaybillId:
      name: id
      in: path
      description: Unique Cargospot internal ID (technical id) for the air waybill or air waybill reference (000-00000000).
      required: true
      schema:
        type: string
        examples:
          - 17869
    handlingOperation:
      name: handlingOperation
      in: query
      description: Indicate if the handling operation is export or import.
      required: true
      schema:
        type: string
        enum:
          - Export
          - Import
        examples:
          - Import
    id:
      name: id
      in: path
      description: Unique Cargospot internal ID for the air waybill.
      required: true
      schema:
        type: string
        examples:
          - 17869
    partId:
      name: partId
      in: path
      description: Unique Cargospot internal ID for the part shipment. The Cargospot Retrieve Acceptance Details for an Air Waybill API can be used for retrieving this ID.
      required: true
      schema:
        type: string
        examples:
          - 13425
    deliveryId:
      name: id
      in: path
      required: true
      description: Unique identifier for the delivery record.
      schema:
        type: integer
        examples:
          - 33546822
    uldAcceptanceId:
      name: id
      in: path
      description: Unique Cargospot internal ID (technical id) for the ULD or ULD number.
      required: true
      schema:
        type: string
        examples:
          - AKE31245XS
  requestBodies:
    NewItem:
      description: A JSON object containing item data
      required: true
      content:
        application/json:
          schema:
            type: object
  headers:
    X-RateLimit-Limit:
      description: Request limit per hour
      schema:
        type: integer
      example: 100
    X-RateLimit-Remaining:
      description: Remaining requests for the hour
      schema:
        type: integer
      example: 94
  examples:
    tshirt:
      summary: Sample T-shirt data
      value:
        id: 17
        name: T-shirt
        description: 100% cotton shirt
        categories:
          - clothes
  links: {}
  callbacks: {}
